// @generated by `ruskel-snapshot`; do not edit.
//
// Package: serde-rmpv
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: none

//! Serde integration for the rmpv MessagePack Value type.
//!
//! This crate handles all Serde data model types and includes special support
//! for MessagePack's Ext type through the [`MSGPACK_EXT_STRUCT_NAME`] type
//! annotation.

use std::fmt::{Debug, Display};

use rmpv::Value;
use serde::{de::Deserialize, ser::Serialize};

#[derive(Debug, Display, serde::de::Error, serde::ser::Error, std::error::Error)]
pub enum Error {
    /// Type mismatch error
    TypeError(String),
    /// Data format error
    Format(String),
    /// Unsupported type
    UnsupportedType,
}

/// Deserializes rmpv::Value into a target type.
///
/// # Errors
/// Returns an error if:
/// - Value cannot be deserialized into target type
/// - Value contains unsupported or invalid data for target type
pub fn from_value<'a, T>(s: &'a Value) -> Result<T, Error>
where
    T: Deserialize<'a>;

/// Serializes a type into rmpv::Value.
///
/// # Errors
/// Returns an error if:
/// - Value cannot be serialized
/// - Value contains unsupported types
pub fn to_value<T>(value: &T) -> Result<Value, Error>
where
    T: Serialize;

/// Name of the Serde newtype struct to represent MessagePack's Ext type
///
/// MessagePack Ext format: Ext(tag, binary)
/// Serde data model: _ExtStruct((tag, binary))
///
/// # Example
/// ```rust,ignore
/// #[derive(Debug, PartialEq, Serialize, Deserialize)]
/// #[serde(rename = "_ExtStruct")]
/// struct ExtStruct((i8, Vec<u8>));
/// ```
pub const MSGPACK_EXT_STRUCT_NAME: &str = "_ExtStruct";
